version: '3'

services:
  free90:
    build: .
    image: free90
    volumes:
      - ./:/home/freegame/app/
    ports:
      - 3000:3000
    command: npm run dev

networks:
  external:
   name: free90