name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag freegame90:$(date +%s)

    - name: push
      run: docker push edhubbard1994/freegame90:$(date +%s)
